name: Deploy Qindred

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, json, hash, openssl
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        npm ci
    
    - name: Build Frontend
      run: npm run build
    
    - name: Configure Environment
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        php artisan key:generate
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
    
    - name: Create Build Artifact
      run: |
        # Create directories if they don't exist
        mkdir -p storage/framework/{sessions,views,cache}
        mkdir -p bootstrap/cache
        
        # Create the build artifact
        tar -czf build.tar.gz \
          app/ \
          bootstrap/ \
          config/ \
          database/ \
          public/ \
          resources/ \
          routes/ \
          storage/ \
          vendor/ \
          .env \
          artisan \
          composer.json \
          package.json \
          composer.lock
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build.tar.gz
        retention-days: 1
        if-no-files-found: error
        compression-level: 9
